### PR TITLE
1.19.4

### PR DESCRIPTION
**Pull request by MeeniMc**
Update to 1.19.4
- Migratemappings
- ModelTransformationMode
- WidgetCreator

fixes: #144

### CODE REVIEW

**Comment by tajemniktv** [comment]
Hey, any chance for a prebuilt .jar? 🥲

**Comment by MeeniMc** [comment]
The main author is still active I'll let them publish after they can review.

**Comment by MeeniMc** [comment]
Some mixins are not mapped correctly atm.

**Comment by MeeniMc** [comment]
I fixed the mixin problems ready for review

**Comment by HhiPyrene** [comment]
Crash when open the vanilla option.
[crash-2023-04-09_11.21.24-client.txt](https://github.com/FoundationGames/EnhancedBlockEntities/files/11184727/crash-2023-04-09_11.21.24-client.txt)

**Comment by HhiPyrene** [comment]
Broken when using LambdaBetterGrass.
[latest.log](https://github.com/FoundationGames/EnhancedBlockEntities/files/11184898/latest.log)

**Comment by YukiAyase** [comment]
> Broken when using LambdaBetterGrass. [latest.log](https://github.com/FoundationGames/EnhancedBlockEntities/files/11184898/latest.log)

This incompatibility is caused by EBE
It needs to be fixed on EBE's side
*Its present in 1.19.3*

> Though, in the process of debugging I found out an issue in EBE itself, `INVOKE_ASSIGN` makes it so the injected pack is not present in the `packs` field of the class, using `INVOKE` instead should fix it. This is very important because QSL may recompute namespaces and it could lead to the pack being voided.

-LambdAurora

Maybe consider adding this fix to the PR?
Though, doing so will cause block breaking particles to have missing textures when you have experimental feature ON for beds, chests and signs while having LBG installed

**Comment by FoundationGames** [comment]
I would rather fix this in the 1.19.3 branch (and not have the author of this PR worry about it), it would make things more straightforward when merging

**Comment by MeeniMc** [comment]
tech preview build available. https://github.com/MeeniMc/EnhancedBlockEntities/releases/tag/v0.8.rc.1%2B1.19.4

**Comment by ElBananaa** [comment]
> tech preview build available. https://github.com/MeeniMc/EnhancedBlockEntities/releases/tag/v0.8.rc.1%2B1.19.4

Hey, thanks for the 1.19.4 version above, however, it appears to be broken for me, chests, signs, shulker boxes and beds all appear fully invisible (with and without resource pack).

Here's my entire mod list (just in case). I am using Quilt (Loader v0.18.10).

Any idea on how to fix this?
Thanks! :)

**Comment by YukiAyase** [comment]
> Hey, thanks for the 1.19.4 version above, however, it appears to be broken for me, chests, signs, shulker boxes and beds all appear fully invisible (with and without resource pack).
> 
> Here's my entire mod list (just in case). I am using Quilt (Loader v0.18.10).
> 
> Any idea on how to fix this? Thanks! :)

Since you're on Quilt, I am assuming you're using LambdaBetterGrass along side EBE
There is currently an incompatibility with EBE and LBG that causes this, either removing LBG or EBE is the only current solution

**Comment by ElBananaa** [comment]
> > Hey, thanks for the 1.19.4 version above, however, it appears to be broken for me, chests, signs, shulker boxes and beds all appear fully invisible (with and without resource pack).
> > Here's my entire mod list (just in case). I am using Quilt (Loader v0.18.10).
> > Any idea on how to fix this? Thanks! :)
> 
> Since you're on Quilt, I am assuming you're using LambdaBetterGrass along side EBE There is currently an incompatibility with EBE and LBG that causes this, either removing LBG or EBE is the only current solution

I tried without LBG it still didn't work for a reason I ignore.
Do you have any other ideas?

**Comment by MeeniMc** [comment]
Are you using Quilt loader? Please provide a log.

**Comment by adilrepas** [comment]
> tech preview build available. https://github.com/MeeniMc/EnhancedBlockEntities/releases/tag/v0.8.rc.1%2B1.19.4

it works very well

**Comment by FunkyNico** [comment]
I have tested the build and for some reason has a problem with DashLoader mod (i also tested the 1.20.1 build from [here](https://github.com/Brokkonaut/EnhancedBlockEntities/releases/tag/v1.20.1) with the same mod and didn't have the same issue.)

Logs: [Here](https://mclo.gs/LrYxvYY)

Thanks.

**Comment by FoundationGames** [comment]
Will merge, thanks for contributing!
The actual 1.19.4 update may take a while longer, since decorated pots need to be optimized

**Pull request merged**
