### PR TITLE
Add dashloader support.

### PR DESCRIPTION
**Pull request by alphaqu**
Added the proxy model with the serializer annotations and how DashLoader should handle the models

### CODE REVIEW

**Comment by alphaqu** [comment]
Unsafe lib got added to dev env because of some wierd issues with gradle not getting the dependency from DashLoader.

**Comment by FoundationGames** [comment]
This seems to be quite an interesting implementation. 
I skimmed through the code and found a few uses of if chains, which should be removed in favor of a registry-like implementation for ModelSelector and related. I can implement this myself post merge, however, and will try to do a more thorough and proper review of the code later.

**Comment by alphaqu** [comment]
Please note that this is on the serialization stage which is not at all important, only the undash methods are important in terms of performance as they are what get used on the loading

**Comment by FoundationGames** [comment]
If chains and switch cases (when not used on things like enums) are unclean and make it tedious to add models in the future, which is why the current registry systems exist.
I would much rather have a registry system for those objects that you have assigned IDs in those methods.

**Comment by alphaqu** [comment]
Oh you were talking about switching the entire system out for a better one, sorry for the misunderstanding.

**Comment by alphaqu** [comment]
Whats the status of this being merged?

**Comment by FoundationGames** [comment]
Currently busy with other mods atm.
Keep in mind the next release of EBE will be for 1.17, and I'm not sure if dashloader is updated or not or whether this PR will require changes.
Along with this the PR will also change my general workflow when testing the mod as well, and I am not sure whether this will impede my ability to test the mod in vanilla (without dashloader)
I will consider merging it after the 1.17 release of EBE.

**Comment by alphaqu** [comment]
Dashloader was among the fastest to update to 1.17 and this impl is designed to work without dashloader.

**Comment by ghost** [comment]
how to download
and when will it be implemented?

**Comment by he3als** [comment]
When will this be implemented?

**Comment by alphaqu** [comment]
very out of date

**Pull request closed without merging**
