### PR TITLE
Minor Changes

### PR DESCRIPTION
**Pull request by DragonEggBedrockBreaking**
- Added github actions
- Added download links and instructions
- Fixed gif link
- Bumped loom version so that it builds on jdk 16
- Added homepage and issues tags in `fabric.mod.json`

### CODE REVIEW

**Comment by DragonEggBedrockBreaking** [comment]
Redid #9

**Comment by DragonEggBedrockBreaking** [comment]
- Bumped Loom version again to 0.7-SNAPSHOT
- Bumped Gradle version to 7.0
fixes #19

**Comment by FoundationGames** [comment]
Loom and gradle are being updated in my own uncomitted code. Actions are planned but not until later in development. Thank you anyway for the contribution though! It have been nice if the Loom 0.7/Gradle 7.0 were a separate pull request.

**Comment by DragonEggBedrockBreaking** [comment]
> Loom and gradle are being updated in my own uncomitted code. Actions are planned but not until later in development. Thank you anyway for the contribution though! It have been nice if the Loom 0.7/Gradle 7.0 were a separate pull request.

I can revert the github actions and loom/gradle changes

**Comment by DragonEggBedrockBreaking** [comment]
done

**Pull request closed without merging**
