### PR TITLE
Add ru_ru.json

### PR DESCRIPTION
**Pull request by Felix14-v2**

### CODE REVIEW

**Comment by FoundationGames** [comment]
Some changes have been made to the lang file, which will likely need to be addressed before this PR can be merged.

**Comment by Felix14-v2** [comment]
Done. Probably, I will later have to make some changes to the length of the labels so that the text fits on the new buttons.

**Comment by Felix14-v2** [comment]
@FoundationGames , can this PR be merged, or are you planning to add new text elements in future? 
Maybe I should close PR and reopen it for the 1.18 branch?

**Comment by FoundationGames** [comment]
The PR looks very good, however the colored text is using old formatting characters (Minecraft will eventually stop supporting those so using them in translation files is discouraged) and it breaks visual parity with English.  I do like the idea of having the text be colored, and I have another pending pull request that restructures the button texts and allows me to do this.

I may just merge the PR as is once I finish those changes, and make the changes to this translation file manually.

**Comment by triphora** [comment]
> however the colored text is using old formatting characters (Minecraft will eventually stop supporting those so using them in translation files is discouraged)

As opposed to new formatting characters? What other solution is there?

**Comment by FoundationGames** [comment]
Since old formatting characters are deprecated in favor of json text components (not definable through translation files), the ability to format translations is also likely deprecated

**Comment by Felix14-v2** [comment]
I can remove the formatting of the text for now and leave only translation until the formatting situation is resolved.

**Pull request closed without merging**
