### PR TITLE
Update to 1.20.6

### LINKED ISSUE #210: 1.20.5 and 1.20.6 support
No more I want to saying.

### PR DESCRIPTION
**Pull request by Rektroth**
ARRP and SpruceUI both need official updates for 1.20.5/6 before this can be merged.

Preview can be downloaded from the fork repo.

Closes #210.

### CODE REVIEW

**Comment by KennyDevT** [comment]
The preview crashes on boot.

**Comment by KennyDevT** [comment]
[Log](https://mclo.gs/RP97N4A#L265)

**Comment by Rektroth** [comment]
Looks like a problem with my changes to ARRP being triggered by one of your other mods and/or a resource pack, which I don't feel like diagnosing.
ARRP will need a proper update by someone who actually knows what they're doing.

**Comment by venaminecraft** [comment]
Having issues as well. But thanks for the update!

**Pull request closed without merging**
